version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "examples/**"
    groups:
      devDependencies:
        dependency-type: "development"
