version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "examples/**"
    # Only allow updates for production dependencies
    allow:
      - dependency-type: "production"
